# Generated by Django 4.0.5 on 2023-01-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_desc', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('safety_stock', models.IntegerField()),
                ('note', models.TextField(max_length=200)),
            ],
        ),
    ]
