# Generated by Django 4.0.5 on 2023-01-15 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField(max_length=200)),
                ('in_use', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('hardware_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_desc', models.TextField(max_length=200)),
                ('in_use', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_desc', models.TextField(max_length=200)),
                ('price', models.FloatField()),
                ('safety_stock', models.IntegerField()),
                ('note', models.TextField(max_length=200, null=True)),
                ('in_use', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_desc', models.TextField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=20)),
                ('quantity', models.FloatField()),
                ('tran_datetime', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOnStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_stock', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemForHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('hardware_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.hardwaretype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.item')),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mac', models.TextField(max_length=200, null=True)),
                ('location', models.TextField(max_length=200)),
                ('in_use', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.order')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.hardwaretype')),
            ],
        ),
    ]
