# Generated by Django 4.0.5 on 2023-01-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
