# Generated by Django 4.0.5 on 2023-01-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware_type',
            fields=[
                ('hardware_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_desc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item_on_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_stock', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.item')),
            ],
        ),
        migrations.CreateModel(
            name='Item_for_hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('hardware_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.hardware_type')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.item')),
            ],
        ),
    ]
