# Generated by Django 4.0.5 on 2023-01-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_hardware_type_item_on_stock_item_for_hardware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
