# Generated by Django 4.0.5 on 2023-01-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_alter_item_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
