# Generated by Django 4.0.5 on 2023-01-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0003_order_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtran',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sklad.order'),
        ),
    ]
