# Generated by Django 4.0.5 on 2023-01-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0005_remove_itemtran_tran_datetime_itemtran_tran_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtran',
            name='tran_type',
        ),
        migrations.AlterField(
            model_name='itemtran',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
