# Generated by Django 4.0.5 on 2023-01-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0006_remove_itemtran_tran_type_alter_itemtran_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtran',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
