# Generated by Django 4.0.5 on 2023-01-22 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0007_alter_itemtran_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardware',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='itemtran',
            options={'ordering': ['-tran_created']},
        ),
        migrations.AddField(
            model_name='hardware',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
