# Generated by Django 4.0.5 on 2023-01-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0009_alter_hardware_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='in_use',
            field=models.BooleanField(),
        ),
    ]
