# Generated by Django 4.0.5 on 2023-01-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0012_alter_hardwaretype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_num']},
        ),
    ]
